name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
  minify:
      steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so auto-minify job can access it
        - uses: actions/checkout@v2

        - name: Auto Minify
          uses: nizarmah/auto-minify@v2.1

        # Auto commits minified files to the repository
        # Ignore it if you don't want to commit the files to the repository 
        - name: Auto committing minified files
          uses: stefanzweifel/git-auto-commit-action@v4
          with:
            commit_message: "Github Action: Auto Minified JS and CSS files"
            branch: ${{ github.ref }}
